CREATE TABLE `aasc_db_1`.`student_reg_form` (
   `id` INT NOT NULL AUTO_INCREMENT , 
   `full_name` VARCHAR(255) NOT NULL , 
   `ssc_hall_ticket_no` INT NOT NULL , 
   `aadhaar_number` CHAR(12) NOT NULL , 
   `ssc_pass_year` YEAR NOT NULL , 
   `email_id` VARCHAR(255) NOT NULL , 
   `mobile_no` CHAR(10) NOT NULL , 
   `gender` ENUM('Male','Female') NOT NULL , 
   `age` INT NOT NULL , 
   `dob` DATE NOT NULL , 
   `mother_tongue` VARCHAR(255) NOT NULL , 
   `ll_language` ENUM('Telugu','Hindi') NOT NULL , 
   `religion` VARCHAR(255) NOT NULL , 
   `caste_category` VARCHAR(255) NOT NULL , 
   `identification_marks` TEXT NOT NULL , 
   `extra_curicular_activities` SET('PH','Sports','NCC','NSS','Ex-Service Man') NOT NULL , 
   `father_name` VARCHAR(255) NOT NULL , 
   `father_aadhaar_no` CHAR(12) NOT NULL , 
   `mother_name` VARCHAR(255) NOT NULL , 
   `mother_aadhaar_no` CHAR(12) NOT NULL , 
   `guardian_name` VARCHAR(255) NOT NULL , 
   `guardian_aadhaar_no` CHAR(12) NOT NULL , 
   `father_occupation` VARCHAR(255) NOT NULL , 
   `annual_income` DECIMAL(10, 2) NOT NULL , 
   `parent_mobile_no` CHAR(10) NOT NULL , 
   `door_number` VARCHAR(255) NOT NULL , 
   `street_name` VARCHAR(255) NOT NULL , 
   `village` VARCHAR(255) NOT NULL , 
   `mandal` VARCHAR(255) NOT NULL , 
   `district` VARCHAR(255) NOT NULL , 
   `state` VARCHAR(255) NOT NULL , 
   `pincode` CHAR(6) NOT NULL , 
   `school_college` VARCHAR(255) NOT NULL , 
   `english_gpa` DECIMAL(3,2) NOT NULL , 
   `maths_gpa` DECIMAL(3,2) NOT NULL , 
   `general_science_gpa` DECIMAL(3,2) NOT NULL , 
   `social_studies_gpa` DECIMAL(3,2) NOT NULL , 
   `total_marks_grade` INT NOT NULL , 
   `perc_gpa` DECIMAL(5,2) NOT NULL , 
   `year_of_pass` YEAR NOT NULL , 
   `pass_type` ENUM('Regular','Compartmental','Open School') NOT NULL , 
   `board_name` VARCHAR(255) NOT NULL , 
   `hall_ticket_no` INT NOT NULL , 
   `place_of_study` VARCHAR(255) NOT NULL , 
   `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
   `updated_at` DATETIME on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
   PRIMARY KEY (`id`), 
   UNIQUE `full_name` (`full_name`)
) ENGINE = InnoDB;